[build]
  functions = "netlify/functions"
  command = "npx prisma generate && npm run build"
  publish = "dist"

[functions]
  node_bundler = "esbuild"
  included_files = ["prisma/**/*"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
