services:
  - type: web
    name: bitespeed-identity-reconciliation
    env: node
    plan: free
    buildCommand: |
      npm ci
      npx prisma generate
      npm run build
    startCommand: npm start
    healthCheckPath: /api/identify
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: bitespeed-db
          property: connectionString

databases:
  - name: bitespeed-db
    plan: free
    ipAllowList: []