services:
  - type: web
    name: bitespeed-identity-reconciliation
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm run migrate && npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: bitespeed-postgres
          property: connectionString

databases:
  - name: bitespeed-postgres
    plan: free
    ipAllowList: [] # only allow internal connections