services:
  - type: web
    name: bitespeed-identity-reconciliation
    env: node
    plan: free
    buildCommand: npm install && npm run build && npm run migrate
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bitespeed-db
          property: connectionString
      - key: NODE_ENV
        value: production

databases:
  - name: bitespeed-db
    databaseName: postgres
    user: postgres