services:
  - type: web
    name: bitespeed-identity-reconciliation
    env: node
    plan: free
    buildCommand: |
      npm ci
      npx prisma generate
      npm run build
    startCommand: |
      npx prisma migrate deploy
      npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
      - key: DATABASE_URL
        fromDatabase:
          name: bitespeed-db
          property: connectionString

databases:
  - name: bitespeed-db
    plan: free